### ISSUE TITLE
[1.18.2] Infinite EMI reloading

### ISSUE THREAD

**Issue by ConqAra** [badasintended/slotlink#151]
**Setup**
- Minecraft: 1.18.2
- Fabric API: 0.67.0
- slotlink: 4.4.0

**Problem**
Infinite EMI reloading... on server when installing mod on both client and server

![image](https://user-images.githubusercontent.com/76233356/218556321-48b38e8e-2b72-43f1-9f40-9420a9819e23.png)

**Comment by ConqAra** [comment]
Edit: this does this on client-side only too. I'm not even able to load this in singleplayer!

**Comment by ConqAra** [comment]
Log: 
[14:45:23] [Thread-43/ERROR]: Uncaught exception in thread "Thread-43" java.lang.NoClassDefFoundError: dev/emi/emi/api/recipe/handler/EmiRecipeHandler 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.10.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.10.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	at badasintended.slotlink.compat.recipe.EmiRecipeViewer.register(EmiRecipeViewer.kt:47) ~[slotlink-4.4.0.jar:?] 	at dev.emi.emi.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:115) ~[emi-0.5.3+1.18.2.jar:?] 	at java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.lang.ClassNotFoundException: dev.emi.emi.api.recipe.handler.EmiRecipeHandler 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.10.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	... 11 more

**Comment by ConqAra** [comment]
Nevermind, I had to update EMI. Works now.
