### ISSUE TITLE
Import/Export/Link Cables not connecting on sides other than North.

### ISSUE THREAD

**Issue by Jkosio23** [badasintended/slotlink#48]
I've checked on  1.1.6, 1.1.5, and 1.1.4 and none of them have the interfacing cables that can even connect to sides other than north, no matter what direction I place them from.

**Comment by deirn** [comment]
cant seem to reproduce it, do you connect it to vanilla chest or modded one?

**Comment by Jkosio23** [comment]
Modded, I'm on All of fabric 3 and I manually updated your mod, might need to update fabric itself now that I think about it. I'm on my phone now so I'll get back to you later.

**Comment by deirn** [comment]
yeah i need your modlist, or at least storage mods you use

**Comment by danke969** [comment]
I have the same issue, link cables only seem to connect to North. I´m on All of fabric 1.5.3 and I updated Slotlink to latest version. Fabric updated too
Also when I tried to connect another inventory on other side and open Request Block console spammed this:
(happens with Vanilla chests and ExpandedStorage)

 [16:38:06] [Server thread/FATAL]: Error executing task on Server
 java.lang.NullPointerException: null
	at badasintended.slotlink.block.MasterBlock$onUse$1.applyAsInt(MasterBlock.java:68) ~[slotlink-1.2+minecraft- 1.16.1.jar:?]
	at badasintended.slotlink.block.MasterBlock$onUse$1.applyAsInt(MasterBlock.java:20) ~[slotlink-1.2+minecraft- 
 1.16.1.jar:?]
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210) ~[?:1.8.0_265]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_265]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:479) ~[?:1.8.0_265]
	at java.util.stream.IntPipeline.sum(IntPipeline.java:437) ~[?:1.8.0_265]
	at badasintended.slotlink.block.MasterBlock.method_9534(MasterBlock.java:68) ~[slotlink-1.2+minecraft-1.16.1.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:893) ~[intermediary-minecraft-1.16.1- 
 client.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:328) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:976) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-minecraft-1.16.1- 
 client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]




![2020-09-04_16 38 38](https://user-images.githubusercontent.com/68042381/92289385-8a0c7500-eecd-11ea-9fb6-bfb1c5364e2c.png)
![2020-09-04_16 39 50](https://user-images.githubusercontent.com/68042381/92289389-8bd63880-eecd-11ea-869b-aea6d60f4277.png)

**Comment by deirn** [comment]
alright, thanks. I'll look to it later

**Comment by deirn** [comment]
got around to test it, it seems that other mod is causing this, since it works fine with only slotlink installed

**Comment by redcreeper14385** [comment]
I've also experienced this bug, and also with ExpandedStorage chests so it could be on their end.
