### ISSUE TITLE
Remotes Assume A Hotbar of Size 9

### ISSUE THREAD

**Issue by gudenau** [badasintended/slotlink#81]
**Setup**
- Minecraft: 1.16.5
- Fabric API: 0.30.0+1.16
- slotlink: 00f7c5c4258ff8753d6d32d4fa4d734ff0442a00
- Large Bar: 0.0.0

**Problem**
When using a remote from a hotbar slot greater than 9 an index out of bounds exception is thrown.

```
 java.lang.IndexOutOfBoundsException: Index 46 out of bounds for length 46
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.set(ArrayList.java:441) ~[?:?]
	at badasintended.slotlink.screen.RemoteScreenHandler.resize(RemoteScreenHandler.kt:41) ~[main/:?]
	at badasintended.slotlink.client.gui.screen.RequestScreen.init(RequestScreen.kt:184) ~[main/:?]
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient.java:883) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:82) ~[fabric-screen-handler-api-v1-1.1.1+ca58154a7d@net.fabricmc.yarn.1_16_5.1.16.5+build.4-v2.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$onInitializeClient$0(ClientNetworking.java:51) ~[fabric-screen-handler-api-v1-1.1.1+ca58154a7d@net.fabricmc.yarn.1_16_5.1.16.5+build.4-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:136) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:22) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:109) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:97) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:979) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:624) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1@net.fabricmc.yarn.1_16_5.1.16.5+build.4-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1@net.fabricmc.yarn.1_16_5.1.16.5+build.4-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1@net.fabricmc.yarn.1_16_5.1.16.5+build.4-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Reproduction**
1. Create a network
2. Bind a remote
3. Use from slots 10-18

**Remarks**
Should be easy to fix by respecting `PlayerInventory.getHotbarSize()I`

**Comment by gudenau** [comment]
Related issue in Large Bar: https://github.com/gudenau/minecraft-largebar/issues/1
